[package]
name = "flux-rs"
version = "0.1.0"
authors = ["Tom Scogland <scogland1@llnl.gov>"]
edition = "2018"

[dependencies]
error-chain = "0.12.0"
serde = "1.0.89"
serde_json = "1.0"

[dependencies.flux-sys]
git = "https://github.com/flux-framework/flux-sys-rs"
branch = "master"

